/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as boxSol from "./box.sol";
export * as governanceSol from "./governance.sol";
export * as timelockSol from "./timelock.sol";
export * as votetokenSol from "./votetoken.sol";
