/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as boxSol from "./box.sol";
export type { boxSol };
import type * as governanceSol from "./governance.sol";
export type { governanceSol };
import type * as timelockSol from "./timelock.sol";
export type { timelockSol };
import type * as votetokenSol from "./votetoken.sol";
export type { votetokenSol };
